/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    CheckDone
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_HelloJNI_CheckDone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
